"use client";

import { getActionLabel } from "@/lib/chat/action-labels";

/**
 * Pure presentational component. Renders a list of MCP-orchestrator staged
 * actions with checkboxes, status indicators, and per-row summaries. Holds
 * NO state — `checkedIds` and `appliedStatuses` are controlled by the
 * parent, which also owns the submit logic.
 *
 * This is the single approval primitive shared between chat and /review.
 * Anywhere a list of staged tool calls needs human approval, mount this
 * and pass the same shape from `chat_messages.metadata.staged_actions`.
 */

export interface StagedAction {
  id: string;
  tool: string;
  /** Human-readable description of what this action will do, generated by
   *  the tool's dryRun handler when the orchestrator stages the call. */
  summary: string;
  /** Per-action status, persisted on chat_messages.metadata.applied_statuses
   *  after submission. Possible values: "applied" | "failed" | "rejected".
   *  Absent / "pending" means awaiting user decision. */
  status?: string | undefined;
  /** Error message when status === "failed". */
  error?: string;
}

interface Props {
  actions: StagedAction[];
  /** Currently-checked action ids (controlled). */
  checkedIds: Set<string>;
  /** Toggle a single action's checked state. */
  onToggle: (id: string) => void;
  /** Disable all checkboxes (e.g. while a submit is in flight). */
  disabled?: boolean;
  /** Optional banner heading. Defaults to "Staged Actions". */
  heading?: string;
  /** Optional grouping. When provided, actions are bucketed by the
   *  returned `key` and rendered under a per-group header (`label`). The
   *  default is flat — no grouping. Used by chat/review to collapse the
   *  N-actions-per-document explosion into one card per doc, since the
   *  user thinks in documents not actions. Returning null leaves the
   *  action ungrouped (rendered in a fallback "Other" section). */
  groupBy?: (action: StagedAction) => { key: string; label: string } | null;
}

export function StagedActionsList({
  actions,
  checkedIds,
  onToggle,
  disabled = false,
  heading = "Staged Actions",
  groupBy,
}: Props) {
  if (actions.length === 0) return null;

  // Bucket by groupBy() when provided. Preserve action order within each
  // bucket and the order in which buckets first appear (so the visual
  // grouping reflects the agent's call sequence).
  let groups: Array<{ key: string; label: string | null; actions: StagedAction[] }>;
  if (groupBy) {
    const buckets = new Map<string, { key: string; label: string | null; actions: StagedAction[] }>();
    for (const a of actions) {
      const g = groupBy(a);
      const key = g?.key ?? "__other__";
      const label = g?.label ?? null;
      const bucket = buckets.get(key);
      if (bucket) {
        bucket.actions.push(a);
      } else {
        buckets.set(key, { key, label, actions: [a] });
      }
    }
    groups = Array.from(buckets.values());
  } else {
    groups = [{ key: "__all__", label: null, actions }];
  }

  return (
    <div
      style={{
        background: "#f8f7f4",
        borderRadius: 10,
        padding: 12,
        border: "1px solid #e8e6df",
      }}
    >
      <div
        style={{
          fontSize: 12,
          fontWeight: 600,
          color: "#9494a0",
          textTransform: "uppercase",
          letterSpacing: "0.06em",
          marginBottom: 8,
        }}
      >
        {heading}
      </div>

      {groups.map((group) => (
        <div key={group.key} style={{ marginBottom: groups.length > 1 ? 12 : 0 }}>
          {group.label && (
            <div
              style={{
                fontSize: 11,
                fontWeight: 600,
                color: "#1a1a1f",
                marginTop: 4,
                marginBottom: 4,
                paddingBottom: 4,
                borderBottom: "1px solid #e8e6df",
              }}
            >
              {group.label}
              {group.actions.length > 1 && (
                <span style={{ fontWeight: 400, color: "#9494a0", marginLeft: 6 }}>
                  · {group.actions.length} actions
                </span>
              )}
            </div>
          )}
          {group.actions.map((staged) => {
        const isApplied = staged.status === "applied";
        const isRejected = staged.status === "rejected";
        const isFailed = staged.status === "failed";
        const isPending = !staged.status || staged.status === "pending";
        const label = getActionLabel(staged.tool);

        return (
          <div
            key={staged.id}
            style={{
              display: "flex",
              alignItems: "flex-start",
              gap: 8,
              padding: "6px 0",
              borderBottom: "1px solid #e8e6df",
              opacity: isRejected ? 0.4 : 1,
            }}
          >
            <input
              type="checkbox"
              checked={isApplied || checkedIds.has(staged.id)}
              disabled={!isPending || disabled}
              onChange={() => onToggle(staged.id)}
              style={{ marginTop: 2 }}
            />
            <div style={{ flex: 1 }}>
              <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
                <span
                  style={{
                    fontSize: 10,
                    fontWeight: 600,
                    padding: "1px 6px",
                    borderRadius: 4,
                    background: `${label.color}15`,
                    color: label.color,
                    textTransform: "uppercase",
                  }}
                >
                  {label.label}
                </span>
                {isApplied && (
                  <span style={{ fontSize: 11, color: "#2d8a4e" }}>✓ Applied</span>
                )}
                {isFailed && (
                  <span style={{ fontSize: 11, color: "#c73e3e" }}>✗ Failed</span>
                )}
                {isRejected && (
                  <span style={{ fontSize: 11, color: "#9494a0" }}>Skipped</span>
                )}
              </div>
              <div style={{ fontSize: 12, color: "#1a1a1f", marginTop: 2 }}>
                {staged.summary}
              </div>
              {isFailed && staged.error && (
                <div
                  style={{
                    marginTop: 6,
                    padding: "6px 10px",
                    background: "#fbe8e8",
                    border: "1px solid #f4b8b8",
                    borderRadius: 6,
                    color: "#7a1818",
                    fontSize: 11,
                    lineHeight: 1.4,
                    wordBreak: "break-word",
                  }}
                >
                  <strong>Why it failed:</strong> {staged.error}
                </div>
              )}
            </div>
          </div>
        );
      })}
        </div>
      ))}
    </div>
  );
}
