-- Enum types for Plinth AI
CREATE TYPE entity_type AS ENUM ('holding_company','investment_fund','operating_company','real_estate','special_purpose','management_company','trust','other');
CREATE TYPE entity_status AS ENUM ('active','inactive','dissolved','suspended','pending_formation','converting');
CREATE TYPE trust_type AS ENUM ('revocable','irrevocable');
CREATE TYPE trust_role_type AS ENUM ('grantor','trustee','successor_trustee','beneficiary','contingent_beneficiary','trust_protector','investment_advisor','distribution_advisor','trust_counsel');
CREATE TYPE directory_entry_type AS ENUM ('individual','external_entity','trust');
CREATE TYPE jurisdiction AS ENUM ('AL','AK','AZ','AR','CA','CO','CT','DE','DC','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY','PR','GU','VI','AS','foreign');
CREATE TYPE relationship_type AS ENUM ('profit_share','fixed_fee','management_fee','performance_fee','equity','loan','guarantee','service_agreement','license','lease','other');
CREATE TYPE payment_frequency AS ENUM ('one_time','monthly','quarterly','semi_annual','annual','upon_event','na');
CREATE TYPE relationship_status AS ENUM ('active','expired','terminated','pending','disputed');
CREATE TYPE investor_type AS ENUM ('individual','entity','external_fund','family_office','institutional','trust','other');
CREATE TYPE document_type AS ENUM ('operating_agreement','articles_of_organization','certificate_of_formation','amendment','resolution','consent','trust_agreement','trust_amendment','ein_letter','k1','tax_return','financial_statement','audit_report','subscription_agreement','side_letter','ppm','capital_call_notice','distribution_notice','schedule_of_beneficiaries','management_agreement','advisory_agreement','promissory_note','guarantee','service_agreement','lease','annual_report_filing','statement_of_information','franchise_tax_receipt','foreign_qualification','certificate_of_good_standing','insurance_policy','insurance_certificate','correspondence','other');
CREATE TYPE filing_type AS ENUM ('annual_report','biennial_report','statement_of_information','franchise_tax','annual_list','periodic_report','foreign_qualification_renewal','other');
CREATE TYPE filing_status AS ENUM ('current','due_soon','overdue','not_required','exempt');
CREATE TYPE custom_field_type AS ENUM ('text','checkbox','date','number','dropdown','url');
CREATE TYPE user_role AS ENUM ('admin','editor','viewer');
